defaults:
  - mujoco_playground_base

task_name: G1MocapTracking
task_params:
  ctrl_dt: 0.02
  sim_dt: 0.002
  episode_length: 1000
  action_repeat: 1
  action_scale: 0.5
  noise_config:
    level: 0.0
    scales:
      joint_pos: 0.03
      joint_vel: 1.5
      gravity: 0.05
      linvel: 0.1
      gyro: 0.2
  reward_config:
    scales:
      tracking_lin_vel: 1.0
      tracking_ang_vel: 0.75
      pose: 0.65
      velocity: 0.1
      end_effector: 0.15
      com: 0.1
      com_orientation: 0.1
      control: 0.0
      action_rate: 0.0
      torques: 0.0
      left_pos: 0.0
      right_pos: 0.0
      left_ori: 0.0
      right_ori: 0.0
      alive: 0.0
      termination: -10.0
    pose_exp_coeff: 0.5
    velocity_exp_coeff: 0.1
    end_effector_exp_coeff: 40.0
    com_exp_coeff: 10.0
    com_orientation_exp_coeff: 2.0
    control_exp_coeff: 0.01
    foot_position_exp_coeff: 10.0
    foot_orientation_exp_coeff: 2.0
  reference_path: ss2r/benchmark_suites/mujoco_playground/g1_mocap_tracking/walk1_subject1.npz
  random_start: true
  loop_reference: true
  reset_noise_scale: 0.0
  termination_height: 0.45
  termination_upvector_z: 0.0

train_params: {}

eval_params: {}
