defaults:
  - mujoco_playground_base

task_name: G1MocapTracking
task_params:
  ctrl_dt: 0.02
  sim_dt: 0.002
  episode_length: 1000
  action_repeat: 1
  action_scale: 0.5
  noise_config:
    level: 1.0
    scales:
      joint_pos: 0.03
      joint_vel: 1.5
      gravity: 0.05
      linvel: 0.1
      gyro: 0.2
  reward_config:
    scales:
      root_pos: 0.5
      root_ori: 0.5
      pose: 1.0
      body_ori: 1.0
      body_lin_vel: 1.0
      body_ang_vel: 1.0
      action_rate: -0.1
      joint_limit: -10.0
      self_collisions: -10.0
      left_pos: 0.0
      right_pos: 0.0
      left_ori: 0.0
      right_ori: 0.0
      alive: 0.0
      termination: 0.0
    stds:
      root_pos: 0.3
      root_ori: 0.4
      pose: 0.3
      body_ori: 0.4
      body_lin_vel: 1.0
      body_ang_vel: 3.14
      left_pos: 0.3
      right_pos: 0.3
      left_ori: 0.4
      right_ori: 0.4
  reference_path: ss2r/benchmark_suites/mujoco_playground/g1_mocap_tracking/walk1_subject1.npz
  random_start: true
  loop_reference: true
  reset_noise_scale: 0.01
  termination_height: 0.45
  termination_upvector_z: 0.0

train_params: {}

eval_params: {}
