defaults:
  - mujoco_playground_base

task_name: G1MocapTracking
task_params:
  ctrl_dt: 0.02
  sim_dt: 0.002
  episode_length: 1000
  loco:
    dataset_name: dance1_subject3
    reference_source: hf
    reference_repo_id: robfiras/loco-mujoco-datasets
    reference_repo_type: dataset
    reference_dir: Lafan1/mocap/UnitreeG1
