name: hydrax_mpc

# Uses mujoco_playground env._get_reward for running cost.
running_cost_scale: 1.0
terminal_cost_scale: 0.0

# Use MPPI controller only.
controller_kwargs:
  num_samples: 128
  noise_level: 0.1
  temperature: 0.1
  num_randomizations: 1
  seed: 0
  plan_horizon: 1.0
  spline_type: zero
  num_knots: 4
  iterations: 1

# Optional action bounds
action_low: -1.0
action_high: 1.0
